In [2]:
%load_ext kedro.ipython

The kedro.ipython extension is already loaded. To reload it, use:
  %reload_ext kedro.ipython

In [9]:
companies =catalog.load("companies")
companies.head()

[09/11/26 17:35:33] INFO     Loading data from companies (CSVDataset)...                       ]8;id=883151;file://c:\Users\kapab\OneDrive\Desktop\KedroLabs\venv\Lib\site-packages\kedro\io\data_catalog.py\data_catalog.py]8;;\:]8;id=282551;file://c:\Users\kapab\OneDrive\Desktop\KedroLabs\venv\Lib\site-packages\kedro\io\data_catalog.py#1046\1046]8;;\

,id,company_rating,company_location,total_fleet_count,iata_approved
0,3888,100%,Isle of Man,1.0,f
1,46728,100%,NaN,1.0,f
2,34618,38%,Isle of Man,1.0,f
3,28619,100%,Bosnia and Herzegovina,1.0,f
4,8240,NaN,Chile,1.0,t

In [10]:
companies.dtypes

id                     int64
company_rating        object
company_location      object
total_fleet_count    float64
iata_approved         object
dtype: object

In [11]:
import pandas as pd
def _is_true(c: pd.Series) -> pd.Series:
    return c == "t"

In [12]:
companies["iata_approved"] = _is_true(companies["iata_approved"])
companies.head()

,id,company_rating,company_location,total_fleet_count,iata_approved
0,3888,100%,Isle of Man,1.0,False
1,46728,100%,NaN,1.0,False
2,34618,38%,Isle of Man,1.0,False
3,28619,100%,Bosnia and Herzegovina,1.0,False
4,8240,NaN,Chile,1.0,True

In [13]:
def parse_percent(c: pd.Series) -> pd.Series:
    return c.str.replace("%","").astype(float)

In [14]:
companies["company_rating"]= parse_percent(companies["company_rating"])
companies.head()

,id,company_rating,company_location,total_fleet_count,iata_approved
0,3888,100.0,Isle of Man,1.0,False
1,46728,100.0,NaN,1.0,False
2,34618,38.0,Isle of Man,1.0,False
3,28619,100.0,Bosnia and Herzegovina,1.0,False
4,8240,NaN,Chile,1.0,True

In [15]:
shuttles = catalog.load("shuttles")
shuttles.head()

[09/11/26 17:36:01] INFO     Loading data from shuttles (ExcelDataset)...                      ]8;id=139654;file://c:\Users\kapab\OneDrive\Desktop\KedroLabs\venv\Lib\site-packages\kedro\io\data_catalog.py\data_catalog.py]8;;\:]8;id=136185;file://c:\Users\kapab\OneDrive\Desktop\KedroLabs\venv\Lib\site-packages\kedro\io\data_catalog.py#1046\1046]8;;\

,id,shuttle_location,shuttle_type,engine_type,engine_vendor,engines,passenger_capacity,cancellation_policy,crew,d_check_complete,moon_clearance_complete,price,company_id
0,45163,Sao Tome and Principe,Type V5,Plasma,ThetaBase Services,2.0,4,moderate,2.0,f,f,"$1,715.0",32413
1,49438,Wallis and Futuna,Type V2,Plasma,ThetaBase Services,3.0,5,moderate,3.0,f,f,"$3,405.0",14122
2,10750,Niue,Type F5,Quantum,ThetaBase Services,1.0,2,strict,1.0,t,f,"$1,806.0",47761
3,4146,Malta,Type V2,Quantum,ThetaBase Services,1.0,2,moderate,1.0,f,f,"$1,676.0",26648
4,5067,Malta,Type V2,Plasma,ThetaBase Services,5.0,10,strict,5.0,f,f,"$4,718.0",26648

In [16]:
shuttles.dtypes

id                           int64
shuttle_location            object
shuttle_type                object
engine_type                 object
engine_vendor               object
engines                    float64
passenger_capacity           int64
cancellation_policy         object
crew                       float64
d_check_complete            object
moon_clearance_complete     object
price                       object
company_id                   int64
dtype: object

In [17]:
def parse_money(c: pd.Series) -> pd.Series:
    return c.str.replace("$","").str.replace(",","").astype(float)

In [18]:
shuttles["d_check_complete"] = _is_true(shuttles["d_check_complete"])
shuttles["moon_clearance_complete"] = _is_true(shuttles["moon_clearance_complete"])

In [19]:
shuttles["price"] = parse_money(shuttles["price"])

In [20]:
shuttles.head()

,id,shuttle_location,shuttle_type,engine_type,engine_vendor,engines,passenger_capacity,cancellation_policy,crew,d_check_complete,moon_clearance_complete,price,company_id
0,45163,Sao Tome and Principe,Type V5,Plasma,ThetaBase Services,2.0,4,moderate,2.0,False,False,1715.0,32413
1,49438,Wallis and Futuna,Type V2,Plasma,ThetaBase Services,3.0,5,moderate,3.0,False,False,3405.0,14122
2,10750,Niue,Type F5,Quantum,ThetaBase Services,1.0,2,strict,1.0,True,False,1806.0,47761
3,4146,Malta,Type V2,Quantum,ThetaBase Services,1.0,2,moderate,1.0,False,False,1676.0,26648
4,5067,Malta,Type V2,Plasma,ThetaBase Services,5.0,10,strict,5.0,False,False,4718.0,26648

In [21]:
reviews = catalog.load("reviews")

[09/11/26 17:36:46] INFO     Loading data from reviews (CSVDataset)...                         ]8;id=755594;file://c:\Users\kapab\OneDrive\Desktop\KedroLabs\venv\Lib\site-packages\kedro\io\data_catalog.py\data_catalog.py]8;;\:]8;id=121673;file://c:\Users\kapab\OneDrive\Desktop\KedroLabs\venv\Lib\site-packages\kedro\io\data_catalog.py#1046\1046]8;;\

In [22]:
reviews.head()

,shuttle_id,review_scores_rating,review_scores_comfort,review_scores_amenities,review_scores_trip,review_scores_crew,review_scores_location,review_scores_price,number_of_reviews,reviews_per_month
0,45163,91.0,10.0,9.0,9.0,9.0,9.0,9.0,26,0.77
1,49438,96.0,10.0,10.0,10.0,10.0,10.0,9.0,61,0.62
2,10750,97.0,10.0,10.0,10.0,10.0,10.0,10.0,467,4.66
3,4146,95.0,10.0,10.0,10.0,10.0,9.0,9.0,318,3.22
4,5067,97.0,10.0,9.0,10.0,10.0,9.0,10.0,22,0.29

In [23]:
rated_shuttles = shuttles.merge(reviews, left_on = "id", right_on = "shuttle_id")
rated_shuttles.head()

,id,shuttle_location,shuttle_type,engine_type,engine_vendor,engines,passenger_capacity,cancellation_policy,crew,d_check_complete,...,shuttle_id,review_scores_rating,review_scores_comfort,review_scores_amenities,review_scores_trip,review_scores_crew,review_scores_location,review_scores_price,number_of_reviews,reviews_per_month
0,45163,Sao Tome and Principe,Type V5,Plasma,ThetaBase Services,2.0,4,moderate,2.0,False,...,45163,91.0,10.0,9.0,9.0,9.0,9.0,9.0,26,0.77
1,49438,Wallis and Futuna,Type V2,Plasma,ThetaBase Services,3.0,5,moderate,3.0,False,...,49438,96.0,10.0,10.0,10.0,10.0,10.0,9.0,61,0.62
2,10750,Niue,Type F5,Quantum,ThetaBase Services,1.0,2,strict,1.0,True,...,10750,97.0,10.0,10.0,10.0,10.0,10.0,10.0,467,4.66
3,4146,Malta,Type V2,Quantum,ThetaBase Services,1.0,2,moderate,1.0,False,...,4146,95.0,10.0,10.0,10.0,10.0,9.0,9.0,318,3.22
4,5067,Malta,Type V2,Plasma,ThetaBase Services,5.0,10,strict,5.0,False,...,5067,97.0,10.0,9.0,10.0,10.0,9.0,10.0,22,0.29

In [24]:
model_input_table = rated_shuttles.merge(companies, left_on = "company_id", right_on = "id")
model_input_table.head()

,id_x,shuttle_location,shuttle_type,engine_type,engine_vendor,engines,passenger_capacity,cancellation_policy,crew,d_check_complete,...,review_scores_crew,review_scores_location,review_scores_price,number_of_reviews,reviews_per_month,id_y,company_rating,company_location,total_fleet_count,iata_approved
0,45163,Sao Tome and Principe,Type V5,Plasma,ThetaBase Services,2.0,4,moderate,2.0,False,...,9.0,9.0,9.0,26,0.77,32413,100.0,Faroe Islands,1.0,False
1,49438,Wallis and Futuna,Type V2,Plasma,ThetaBase Services,3.0,5,moderate,3.0,False,...,10.0,10.0,9.0,61,0.62,14122,100.0,Malta,1.0,True
2,10750,Niue,Type F5,Quantum,ThetaBase Services,1.0,2,strict,1.0,True,...,10.0,10.0,10.0,467,4.66,47761,100.0,Niue,2.0,False
3,4146,Malta,Type V2,Quantum,ThetaBase Services,1.0,2,moderate,1.0,False,...,10.0,9.0,9.0,318,3.22,26648,100.0,Niue,2.0,True
4,5067,Malta,Type V2,Plasma,ThetaBase Services,5.0,10,strict,5.0,False,...,10.0,9.0,10.0,22,0.29,26648,100.0,Niue,2.0,True

In [25]:
model_input_table.dropna()

,id_x,shuttle_location,shuttle_type,engine_type,engine_vendor,engines,passenger_capacity,cancellation_policy,crew,d_check_complete,...,review_scores_crew,review_scores_location,review_scores_price,number_of_reviews,reviews_per_month,id_y,company_rating,company_location,total_fleet_count,iata_approved
0,45163,Sao Tome and Principe,Type V5,Plasma,ThetaBase Services,2.0,4,moderate,2.0,False,...,9.0,9.0,9.0,26,0.77,32413,100.0,Faroe Islands,1.0,False
1,49438,Wallis and Futuna,Type V2,Plasma,ThetaBase Services,3.0,5,moderate,3.0,False,...,10.0,10.0,9.0,61,0.62,14122,100.0,Malta,1.0,True
2,10750,Niue,Type F5,Quantum,ThetaBase Services,1.0,2,strict,1.0,True,...,10.0,10.0,10.0,467,4.66,47761,100.0,Niue,2.0,False
3,4146,Malta,Type V2,Quantum,ThetaBase Services,1.0,2,moderate,1.0,False,...,10.0,9.0,9.0,318,3.22,26648,100.0,Niue,2.0,True
4,5067,Malta,Type V2,Plasma,ThetaBase Services,5.0,10,strict,5.0,False,...,10.0,9.0,10.0,22,0.29,26648,100.0,Niue,2.0,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15169,29334,Sao Tome and Principe,Type V7,Quantum,ThetaBase Services,1.0,3,flexible,1.0,True,...,10.0,8.0,10.0,2,2.00,46943,94.0,Peru,2.0,False
15183,49839,Rwanda,Type V5,Nuclear,"Banks, Wood and Phillips",1.0,1,flexible,1.0,True,...,10.0,10.0,10.0,2,2.00,2878,93.0,Bosnia and Herzegovina,3.0,True
15199,59798,Bouvet Island (Bouvetoya),Type V5,Plasma,ThetaBase Services,0.0,7,strict,4.0,True,...,10.0,10.0,10.0,3,3.00,8409,98.0,Maldives,9.0,False
15255,20330,Uzbekistan,Type V5,Quantum,ThetaBase Services,1.0,2,flexible,1.0,False,...,10.0,10.0,10.0,1,1.00,5701,100.0,Costa Rica,1.0,True
15265,16445,Nicaragua,Type V5,Plasma,ThetaBase Services,1.0,1,flexible,3.0,False,...,10.0,10.0,10.0,3,3.00,13728,100.0,Pakistan,1.0,False